### ISSUE TITLE
[sql] syntax highlighting error

### ISSUE THREAD

**Issue by aeschli** [textmate/sql.tmbundle#12]
_From @DenSmoke on December 24, 2015 11:10_

Problems with ' '
![f](https://cloud.githubusercontent.com/assets/16131575/11993935/7015f930-aa50-11e5-857d-e862ff373182.PNG)

_Copied from original issue: Microsoft/vscode#1634_

**Comment by aeschli** [comment]
@DenSmoke Denis, can you paste problematic snippet? It looks like an issue with Unicode characters which I see as well, but I get different errors. Thanks!

**Comment by aeschli** [comment]
_From @DenSmoke on January 8, 2016 16:8_

@aeschli 
5.1.1
INSERT INTO
    ТОВАРЫ(ИЗГОТОВИТЕЛЬ,ШИФР,НАИМЕНОВАНИЕ,ЦЕНА,ЛИМИТ)
VALUES 
    ('ААА','А01','Какой то товар',100,20)
    SELECT \* FROM ТОВАРЫ
5.2.1
INSERT INTO
    СТРОКИ_ПРАЙСА (КОД_ТОВАРА,НАЗВАНИЕ_ТОВАРА,ЦЕНА_ТОВАРА)
    SELECT
        ИЗГОТОВИТЕЛЬ||ШИФР,НАИМЕНОВАНИЕ,ЦЕНА
    FROM 
        ТОВАРЫ
    WHERE
        ИЗГОТОВИТЕЛЬ<>'ЗОМ'

**Comment by aeschli** [comment]
VSCode uses the latest grammar from https://github.com/textmate/sql.tmbundle/blob/master/Syntaxes/SQL.plist

**Comment by kasecato** [comment]
@aeschli delete lines: 570-590, it will work fine.
https://github.com/textmate/sql.tmbundle/compare/master...k--kato:patch-1

**Comment by aeschli** [comment]
The bug was in VS Code's Oniguruma regex library. Closing.

**Comment by aeschli** [comment]
The bug was in VS Code's Oniguruma regex library. Fixed in the January build.

**Comment by gontadu** [comment]
@aeschli So should grammar changes be made just once either on Textmate/VSCode's side or on both?

e.g. https://github.com/Microsoft/vscode/pull/8174

**Comment by aeschli** [comment]
@gontadu Always in both. Preferably in the original repository first.
But this issue was a bug in our regex library.

**Comment by gontadu** [comment]
Thanks @aeschli How often does VSCode's downstream sql grammar sync with the upstream textmate bundle?
